Feature/#206 post blog api
palm-springs/PalmSpringsServer pull request #209
Opened 2023-10-02 16:07 UTC by jinchiim

## PR 확인 사항
PR이 다음 요구 사항을 충족하는지 확인하세요. :

- [x] 커밋 메시지가 [다음 지침](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit)에 따르나요? 
- [x] 추가되는 내용에 대한 테스트를 진행했나요?(버그 해결 / 기능)
- [x] 관련 문서에 추가/반영 되었나요? (버그 해결 보고서 / 기능 문서)

## PR 종류
해당 PR은 어떤 부분에 대한 변화인가요

- [ ] Bug Fix `FIX`(Hotfix)
- [ ] Code Change `MODIFY`
- [x] Feature `FEAT`
- [ ] Code style update (formatting, local variables) `STYLE`
- [x] Refactoring (no functional changes, no api changes) `REFACTOR`
- [ ] Build related changes `BUILD`
- [ ] Documentation content changes `DOCS`
- [ ] Entire application / infrastructure changes `CHORE`
- [ ] Other... (적어주세요 : ) 

## 현재 작업은 어떤 동작인지 설명해주세요

> Issue Number: #206 

## 직전 버전과 비교하여 새롭게 추가된 동작은 어떤 것인지 설명해주세요

- Entity 메타데이터 필드 추가
- Default Category 생성 로직 메서드 분리
- Error 불명확한 명시 명확하게 하도록 변경
- Image 확인 로직 메서드 분리
- Dto Builder 제거 및 필드 추가

## 해당 PR이 다른 영역에 크고 작은 영향을 미치나요?

- [ ] Yes
- [x] No

## 추가 정보

2023-10-02 16:55 UTC, jinchiim commented
최대한 지금까지 해주신 피드백을 바탕으로,
- **메서드 분리가 안되어있는 부분** 
- **필요없는 코드** 그리고 
- **명확하지 않은 에러** 같이

눈에 보였던 점들을 메타데이터 추가하면서 수정해봤어요!

특히 카테고리의 경우 블로그를 생성할때마다 들어가는 고정된 값이기도 하고
BlogService에서 처리할 로직이 아닌 것 같아 돈규씨 말씀대로 메서드 분리를 위해
Enum으로 만들어서 변경해보았습니다!

주시는 피드백을 기준으로 이후에 Entity 연관 관계랑 다른 Method들의 문제점들도 차차 개선해 나갈 계획이라서 
오늘 고친 부분에서 또 부족한 점을 발견하신다면 언제든 의견 말씀해주세용!

2023-10-03 18:31 UTC, yummygyudon requested changes

2023-10-03 18:31 UTC, yummygyudon commented on palm-springs/src/main/java/sopt/org/palmsprings/dashboard/domain/blog/service/BlogService.java
> +        String metaThumbnail = imageService.isChangedImage(blog.getMetaThumbnail(), request.getMetaThumbnail(), blog.getUrl());
여기 또한 imageService의 `isChangedImage` 또한 분리되는게 맞아보인다는 생각입니다.
해당 메서드 내부 로직을 확인해보니 
```java
public String isChangedImage(String originImage, String nowImage, String blogUrl){
        if(!Objects.equals(originImage, nowImage)){
            s3Service.deleteFile(originImage);
            return s3Service.copyImage(nowImage, blogUrl);
        }
        return originImage;
    }
```
이런 식으로 구현되어있는걸 확인했습니다.

우선 
1. 메서드 이름과 맞지 않는 반환값 및 기능
   - 보통 `is~~` 메서드는 반환값이 boolean인 "여부"를 반환하는 메서드에서 사용하는 명명법입니다. → 함수분리는 어떤지


```java
// BlogController 단
public ApiResponse blogUpdate(
            @PathVariable("blogUrl") String url
            , @RequestBody BlogDetailRequestDto request){
        if(!isSameLogo(url, request.getLogo)){
                blogService.updateBlogLogo(url, request.getLogo);
        }
        if(!isSameThumbnail(url, request.getThumbnail)){
                blogService.updateBlogLogo(url, request.getThumbnail);
        }
        if(!isSameMetaThumbnail(url, request.getMetaThumbnail)){
                blogService.updateBlogMetaThumbnail(url, request.getMetaThumbnail);
        }        
        return ApiResponse.success(BlogSuccess.BLOG_MODIFY_SUCCESS);
    }

// BlogService 단
@Transactional(readOnly = true)
public boolean isSameLogo(String url, String newLogo) {
      ...
}
@Transactional
public void updateBlogLogo(String url, String elder, String newLogo) {
      Blog blog = blogRepository.findBy...;
      s3Service.deleteFile(blog.getLogo());
      s3Service.copyFile(newLogo);
      blog.modifyLogo(newLogo);
}

@Transactional(readOnly = true)
public boolean isSameThumbnail(String url, String newThumbnail) {
      ...
}
@Transactional
public void updateBlogThumbnail(String url, String newThumbnail) {
      Blog blog = blogRepository.findBy...;
      s3Service.deleteFile(blog.getThumbnail());
      s3Service.copyFile(newThumbnail);
      blog.modifyThumbnail(newThumbnail);
}
@Transactional(readOnly = true)
public boolean isSameMetaThumbnail(String url, String newMetaThumbnail) {
      ...
}
@Transactional
public void updateBlogMetaThumbnail(String url, String newMetaThumbnail) {
      Blog blog = blogRepository.findBy...;
      s3Service.deleteFile(blog.getMetaThumbnail());
      s3Service.copyFile(newMetaThumbnail);
      blog.modifyMetaThumbnail(newMetaThumbnail);
}
```
이렇게 분리한 후
Controller에서 blogService와 s3Service를 주입받아 각자 호출하는게 결합도를 낮추는게 아닐까라는 생각이 듭니다.

- `isSameLogo(String url, String newLogo)` & `isSameThumbnail(String url, String newThumbnail)` & `isSameMetaImage( 각자 조건 분기 및 적절하게 imageService & s3 service 호출해서 수정 기능 수행 )


S3와 같은 External SDK 구현체는 프로젝트 파일 내 Repository가 없고 Entity 또한 우리가 관리하는 것이 아닌 외부에서 관리되는 것이고
실제로 s3Service를 확인해보니 Repository의 역할을 가졌더라구요.
그렇다면 ImageService에서는 기존 Repository Layer 대신 s3Service가 그 자리를 대신하게 될거라고 생각합니다.

2023-10-03 18:31 UTC, yummygyudon commented on palm-springs/src/main/java/sopt/org/palmsprings/dashboard/domain/blog/service/BlogService.java
> +        String metaThumbnail = imageService.isChangedImage(blog.getMetaThumbnail(), request.getMetaThumbnail(), blog.getUrl());
혹 다른 s3관련 필드에 수정도 다음과같이 결합도 분리하면 좋지 않을까 생각합니다.

2023-10-03 18:38 UTC, jinchiim commented on palm-springs/src/main/java/sopt/org/palmsprings/dashboard/domain/blog/controller/dto/request/BlogDetailRequestDto.java
> -    }
찾아보니 제가 잘못 알고 있던 부분들이 맞아 바로 수정했습니다!
감사합니다요!

2023-10-03 20:46 UTC, jinchiim commented on palm-springs/src/main/java/sopt/org/palmsprings/dashboard/domain/blog/service/BlogService.java
> +        categoryService.addDefaultCategory(blog);
으음 이런 관점도 있네요. 정말 좋은 의견 감사합니다.
우선 해당 메서드를 사용하는 비즈니스 로직이 Category 도메인에서는 존재하지 않습니다!

한번 제 의견을 말씀드리자면,
Category Repository에 접근하여 객체를 저장하는 일은 Category Service에게 책임이 있다고 생각했습니다.

만약 어떠한 블로그 저장에 필요한 반환 값이 존재한다면 Blog Service에 Method가 존재함이 맞겠지만,
반환 값이 없고 필요한 값이 없는데도 불구하고 
Category Repository에 접근하여 Category를 저장한다는 책임이 Blog Service에 있으면 안된다고 생각한 것이 당시의 제 생각이었습니다.

Method란 어떻게 보면 하나의 공장 제품 같은 것인데, 똑 떼어놓고 보면 Category를 저장하는 행위만 함에도,
Blog를 저장할때 발생하는 로직이라는 이유로 해당 Service에 있어야 하는가? 라는 의문이 드는 것 같습니다.

어렵..네요 약 3시간동안 고민했는데도 스스로도 결론이 내려지지 않네요 허허
 
어떠한 반환값을 받아야 하는 부분이라면 이런 고민을 하지 않겠지만 반환값이 없다는 점에서 스스로 고민이 되는 것 같습니다. 
다만 개인적으로는 Repository에만 의존성 주입을 가져가면 깔끔하겠다는 생각이 들어서
아직 완벽한 결론을 내기가 어려운것 같아요.

따라서 좀 더 의견을 듣고 싶은 점이 있는데
Service가 Service를 호출하는 점이 entity 정보를 직접 노출시키면 안된다는 점과 어떻게 연관이 지어지는 부분인지
아직 이해가 되질 않아서 이 부분의 동규씨 지식이 궁금하네요!

늘 새로운 제안/관점 감사해요!

2023-10-05 06:58 UTC, yummygyudon commented on palm-springs/src/main/java/sopt/org/palmsprings/dashboard/domain/blog/service/BlogService.java
> +        categoryService.addDefaultCategory(blog);
- Service에서 Serivce를 의존하는것 : 기존의 3 Layer는 Controller에서 Entity를 직접적으로 노출시키지 않고 책임을 명확히 하기 위해(**책임과 역할 위임** & **메세지를 통한 협업**) 사용되는 모델로서 Service 계층으로 분리하는 방식인데 Service 안에서 또 Service를 의존한다면 **불필요한 계층 재분리**가 일어나게 된다고 생각하며 "도메인 별 서비스"로 분리하는 정책에서 Blog 도메인을 다루는 **Blog Service에서 왜 Category Service를 알아야 하며 왜 로직 상에서 분리된 도에인인 Category 도메인에 영향을 끼치는가** 입니다.
  - 추가적으로 "3 Layer 아키텍쳐" 부분은 상충관계를 따져봐야 하는 요소이기에 다른 개발자분들 중에서는 Controller에서 바로 Repository를 주입받아 사용하는 경우도 있습니다.

2023-10-05 07:05 UTC, yummygyudon commented on palm-springs/src/main/java/sopt/org/palmsprings/dashboard/domain/blog/service/BlogService.java
> +        String metaThumbnail = imageService.isChangedImage(blog.getMetaThumbnail(), request.getMetaThumbnail(), blog.getUrl());
불필요한 트랜젝션은 최소화하자는 의미에서 분리햇습니다.

우선 각 필드에 대한 독립적인 조건 분기를 한 이유는
예를 들어 "로고와 썸네일은 변경이 없는데 메타 썸네일만 변경이 있다" 라는 상황일 떄,
메타 썸네일 파일에 대해서만 편집하면 됨에도 불구하고 무조건 적으로  쿼리를 돌게하는 것이 불필요하다고 생각했구요.

각 필드마다 메서드를 분리한 이유는
서비스 메서드의 역할 분담 + DTO는 서비스 계층으로 왠만해서 넘기지 않기 위해섭니다.
( DTO는 클라이언트와의 통신에서 데이터를 주고 받기위해 사용되는 객체이기에 서비스 계층에서는 이를 알 필요가 없겠죠? 즉, Service의 메서드에서 파라미터로 DTO를 받게 되면 확장성있고 독립되지 않고 DTO에 종속되게 될거에요)

만약 Request 통째로 한 번에 처리하는 메서드라면 너무나도 무거울 거고
만약 지금은 필드가 4개? 그정도지만 만약 10개로 늘어난다면??

물론 10개로 늘어나면 도메인 분리가 필요하겠지만
예시로서 사용한다면 지금과 같은 구조일 경우, 한 메서드에서 10개의 필드에 대한 로직을 전부 처리하는 구조가 되겠죠??

엄청 무거워지고 확장성이 낮아지고 종속적이어지겠죠!!

그래서 필드마다 수정 및 변동 여부 확인을 분리해서 처리하도록 제안을 드려봤습니다!

2023-10-05 15:57 UTC, jinchiim commented on palm-springs/src/main/java/sopt/org/palmsprings/dashboard/domain/blog/service/BlogService.java
> +        categoryService.addDefaultCategory(blog);
음 저는 아직 Category를 정하는 행위만을 하는 책임과 역할을 
blogService에서 가져가야 한다는 점이 납득되기 힘든 것 같습니다.
blogService에서 Category를 저장하는 행위로 Category Repository에 의존성을 가져간다면
오히려 해당 service의 책임이 모호해지는게 아닐까요??

또한 3 Layer 의 핵심은 비즈니스 로직을 Service에 두고, 의존성을 위에서 아래로 향하는 것에 중점이 있고,
따라서 Service에서 타 Service의 의존이 순환 참조가 되는 것이 아닌 이상 저는 이대로 유지하고 싶은 마음이 있는데 
돈규씨는 어떻게 생각하실까용??

2023-10-05 16:04 UTC, jinchiim commented on palm-springs/src/main/java/sopt/org/palmsprings/dashboard/domain/blog/service/BlogService.java
> +        String metaThumbnail = imageService.isChangedImage(blog.getMetaThumbnail(), request.getMetaThumbnail(), blog.getUrl());
> 메타 썸네일 파일에 대해서만 편집하면 됨에도 불구하고 무조건 적으로 쿼리를 돌게하는 것이 불필요하다고 생각했구요.

```java
@Transactional(readOnly = true) public boolean isSameFile(String url, String newUrl) { ... }
```
이렇게 작성하는 경우에도 결국 확인 후 업데이트 과정을 걸치는 건 같은데 혹시 원래 코드를 보고 말씀하신 게 맞을까요??
그렇다면 완전 납득입니다!! 이부분은 바로 수정 해보겠습니다!

사실 지금 수정 가능한 필드가 7개인데,
이미지를 제외한 나머지 부분은 image를 copy하는 로직 같은건 없어,
dto로 그대로 넘겨서 수정하는건 어떨까요?
(name, description, metaName... 같은것들)

2023-10-08 13:07 UTC, yummygyudon commented on palm-springs/src/main/java/sopt/org/palmsprings/dashboard/domain/blog/service/BlogService.java
> +        String metaThumbnail = imageService.isChangedImage(blog.getMetaThumbnail(), request.getMetaThumbnail(), blog.getUrl());
메서드의 파라미터가 많은 것이 맘에 걸리지만...!
이 사안도 개발자마다 서로 다른 의견을 가지는 부분이니
유진님이 하신 방향으로 가시죠

2023-10-08 13:08 UTC, yummygyudon commented on palm-springs/src/main/java/sopt/org/palmsprings/dashboard/domain/blog/service/BlogService.java
> +        categoryService.addDefaultCategory(blog);
이것도 개발자마다 성향 차이이니 유진님이 진행하신 방향으로 가시죠~

2023-10-08 13:08 UTC, yummygyudon commented on palm-springs/src/main/java/sopt/org/palmsprings/dashboard/domain/blog/service/BlogService.java
> +        categoryService.addDefaultCategory(blog);
나중에 개선이 필요하다는 생각이 들 때 바꿔도 되죠~~

2023-10-08 13:08 UTC, yummygyudon approved these changes

2023-10-08 13:08 UTC, yummygyudon commented
이제 작업 진행해야 하니 빠르게 머지하고 진행하시죠

2023-10-08 14:01 UTC, merged